// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tab_menu.Model;

namespace tab_menu.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("tab_menu.Model.Chang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AddProduct");

                    b.Property<string>("CHCodePosti");

                    b.Property<string>("CHColor");

                    b.Property<string>("CHLastNameMaster");

                    b.Property<string>("CHLastNameUser");

                    b.Property<string>("CHNameMaster");

                    b.Property<string>("CHNameProduct");

                    b.Property<string>("CHNameUser");

                    b.Property<bool>("CHProduct");

                    b.Property<string>("CHWeight");

                    b.Property<bool>("IsMaster");

                    b.Property<bool>("IsRrgister");

                    b.HasKey("ID");

                    b.ToTable("changs");
                });

            modelBuilder.Entity("tab_menu.Model.Master", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<string>("Pass")
                        .IsRequired();

                    b.Property<string>("PhonNumber");

                    b.Property<int?>("changID");

                    b.HasKey("ID");

                    b.HasIndex("changID");

                    b.ToTable("masters");
                });

            modelBuilder.Entity("tab_menu.Model.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AdvisePlass");

                    b.Property<string>("Color");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.Property<string>("Weight");

                    b.Property<int?>("changID");

                    b.HasKey("ID");

                    b.HasIndex("changID");

                    b.ToTable("products");
                });

            modelBuilder.Entity("tab_menu.Model.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BoughtProdect");

                    b.Property<string>("CodePosti");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int>("GradeForProduct");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<string>("Pass")
                        .IsRequired();

                    b.Property<string>("PhonNumber");

                    b.Property<int?>("changID");

                    b.HasKey("ID");

                    b.HasIndex("changID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("tab_menu.Model.Master", b =>
                {
                    b.HasOne("tab_menu.Model.Chang", "chang")
                        .WithMany()
                        .HasForeignKey("changID");
                });

            modelBuilder.Entity("tab_menu.Model.Product", b =>
                {
                    b.HasOne("tab_menu.Model.Chang", "chang")
                        .WithMany()
                        .HasForeignKey("changID");
                });

            modelBuilder.Entity("tab_menu.Model.User", b =>
                {
                    b.HasOne("tab_menu.Model.Chang", "chang")
                        .WithMany()
                        .HasForeignKey("changID");
                });
#pragma warning restore 612, 618
        }
    }
}
